version: "3.9"
services:
  db: 
    image: mysql:8.0
    container_name: mysql-db 
    restart: always 
    environment:
      MYSQL_ROOT_PASSWORD: root123 
      MYSQL_DATABASE: tienda 
      MYSQL_USER: user 
      MYSQL_PASSWORD: user123
    ports:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  api:
    build: ./api
    container_name: api-service
    restart: always
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: user123
      DB_NAME: tienda
    ports:
      - "8080:5000"
    depends_on:
      - db

volumes:
  db_data: